### PR TITLE
Parse AST to extract extension API usages

### LINKED ISSUE #6: Accurate browserAPI extraction in metadata.
I would rather update the code so the actual API you use (`browser.runtime.xyz`) shows up.

_Originally posted by @aklinker1 in https://github.com/wxt-dev/examples/pull/4#discussion_r1712675374_
            

refer to: #4 #5

### PR DESCRIPTION
**Pull request by 1natsu172**
close #6

### CODE REVIEW

**Comment by aklinker1** [comment]
One additional case I'd like to support:

https://github.com/wxt-dev/examples/blob/6b2ff01bb1cb588027ffb032ccd98e5113fbf505/examples/active-tab-screenshot/entrypoints/background.ts#L3-L5

I'd rather just write the code below instead, but I wrote it like I did above so the API finding logic worked.

```ts
(browser.action ?? browser.browserAction).onClicked.addListener(...);
```

Didn't see a test case for it, thought I'd mention it.

**Comment by 1natsu172** [comment]
Good point! I'll add that to the supporting syntax.

**Comment by 1natsu172** [comment]
@aklinker1 Alright, parsing and extracting is almost done. From here I think we are in the phase of tweaking the details. 

Only extract method names? Or allow all property names?(dictionary:https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/.repo/sample-list-generator/extension-apis.json), Maximum depth of how many? More test cases? etc... 💭 

Let's continue the conversation.

---

The current implementation follows the [chrome-sample](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/.repo/sample-list-generator), so some differences occur. New APIs can be extracted and some APIs to be removed.

image
image

**Comment by aklinker1** [comment]
I say we allow any depth, but remove any calls to `addListener`

- `browser.storage.session.setAccessLevel` is important to include IMO
- I would prefer to rnot include enum values at all (`browser.offscreen.Reason`) because they're just options to pass into another API with should be detected

Otherwise looks good!

**Comment by 1natsu172** [comment]
@aklinker1 Alright. If depth is not limited, unwanted methods such as `addListener` will be listed and manually excluded in the implementation. This is the same as now.

Enums (like `browser.offscreen.Reason`) could be handled automatically, it should be enough to exclude all with `apiType === "type"` based on the JSON by the chrome-sample.

I'll proceed like that!

**Comment by 1natsu172** [comment]
PR is now ready. Check this when you have time!

**Review by aklinker1 — APPROVED** [review]
Oh yeah, this is nice. Thanks for setting this up! AST is always more consistent than regex lol

**Pull request merged**
